# Generated by Django 4.2.7 on 2025-04-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
