# Generated by Django 4.2.7 on 2024-10-18 08:25

import authentication.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=255, validators=[authentication.models.validate_technologies])),
                ('repository_link', models.URLField()),
                ('how_to_run', models.FileField(blank=True, null=True, upload_to='projects/instructions/')),
                ('creators', models.ManyToManyField(help_text='Select up to 5 student creators', limit_choices_to={'user_type': 'student'}, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
