# Generated by Django 4.2.7 on 2025-04-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(default='TEA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects_taught',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('ETC', 'Electronics and Telecommunications Engineering'), ('PHY', 'Physics'), ('CHE', 'Chemistry'), ('MAT', 'Mathematics'), ('BIO', 'Biology'), ('ENV', 'Environmental Science'), ('ENG', 'English'), ('HIS', 'History'), ('GEO', 'Geography'), ('PHI', 'Philosophy'), ('POL', 'Political Science'), ('ECO', 'Economics'), ('BBA', 'Business Administration'), ('ACC', 'Accounting'), ('MGT', 'Management'), ('FIN', 'Finance'), ('MED', 'Medicine'), ('DEN', 'Dentistry'), ('NUR', 'Nursing'), ('PHR', 'Pharmacy'), ('PSY', 'Psychology'), ('LAW', 'Law'), ('SOC', 'Sociology'), ('EDU', 'Education'), ('ART', 'Fine Arts'), ('MUS', 'Music'), ('ARC', 'Architecture'), ('AGRI', 'Agricultural Science'), ('AVI', 'Aviation Engineering')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
