# Generated by Django 4.2.7 on 2024-10-18 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creators',
        ),
        migrations.AddField(
            model_name='project',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='how_to_run',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
