# Generated by Django 4.2.7 on 2024-10-18 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_project_creators_project_screenshots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.AddField(
            model_name='project',
            name='creators',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'student'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
