# Generated by Django 4.2.7 on 2025-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photos/'),
        ),
    ]
