# Generated by Django 4.2.7 on 2025-02-05 16:34

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.PositiveIntegerField(default=3, validators=[authentication.models.validate_rating]),
        ),
    ]
