# Generated by Django 4.2.7 on 2025-03-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_student_projects_completed_student_projects_involved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='projects_completed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='projects_involved',
        ),
    ]
