# Generated by Django 4.2.7 on 2025-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_student_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bookmarked_projects',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='authentication.project'),
        ),
    ]
